# Form implementation generated from reading ui file 'G:\Projects\MS_VCode\PyQT_Draw_Electric_Signal\Python_Files\main_window.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1042, 580)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(514, 14, 101, 17))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(350, 14, 101, 17))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.get_Sys_portsBtn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.get_Sys_portsBtn.setGeometry(QtCore.QRect(30, 330, 111, 29))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.get_Sys_portsBtn.sizePolicy().hasHeightForWidth())
        self.get_Sys_portsBtn.setSizePolicy(sizePolicy)
        self.get_Sys_portsBtn.setObjectName("get_Sys_portsBtn")
        self.read_Rx_Data_Btn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.read_Rx_Data_Btn.setGeometry(QtCore.QRect(30, 410, 111, 29))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.read_Rx_Data_Btn.sizePolicy().hasHeightForWidth())
        self.read_Rx_Data_Btn.setSizePolicy(sizePolicy)
        self.read_Rx_Data_Btn.setObjectName("read_Rx_Data_Btn")
        self.select_Port_Btn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.select_Port_Btn.setGeometry(QtCore.QRect(30, 370, 136, 29))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.select_Port_Btn.sizePolicy().hasHeightForWidth())
        self.select_Port_Btn.setSizePolicy(sizePolicy)
        self.select_Port_Btn.setObjectName("select_Port_Btn")
        self.time_LstVu = QtWidgets.QListWidget(parent=self.centralwidget)
        self.time_LstVu.setGeometry(QtCore.QRect(340, 40, 120, 301))
        self.time_LstVu.setObjectName("time_LstVu")
        self.volt_LstVu = QtWidgets.QListWidget(parent=self.centralwidget)
        self.volt_LstVu.setGeometry(QtCore.QRect(490, 40, 120, 301))
        self.volt_LstVu.setObjectName("volt_LstVu")
        self.ser_ports_LstVu = QtWidgets.QListWidget(parent=self.centralwidget)
        self.ser_ports_LstVu.setGeometry(QtCore.QRect(19, 130, 281, 180))
        self.ser_ports_LstVu.setObjectName("ser_ports_LstVu")
        self.ser_Port_Info_LabCrl = QtWidgets.QLabel(parent=self.centralwidget)
        self.ser_Port_Info_LabCrl.setGeometry(QtCore.QRect(20, 36, 281, 71))
        self.ser_Port_Info_LabCrl.setObjectName("ser_Port_Info_LabCrl")
        self.volt_time_Tabel = QtWidgets.QTableWidget(parent=self.centralwidget)
        self.volt_time_Tabel.setGeometry(QtCore.QRect(640, 40, 256, 401))
        self.volt_time_Tabel.setObjectName("volt_time_Tabel")
        self.volt_time_Tabel.setColumnCount(0)
        self.volt_time_Tabel.setRowCount(0)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1042, 27))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Voltage (v)"))
        self.label_2.setText(_translate("MainWindow", "Time (Sec)"))
        self.get_Sys_portsBtn.setText(_translate("MainWindow", "Availabell Ports"))
        self.read_Rx_Data_Btn.setText(_translate("MainWindow", "Read Rx Data"))
        self.select_Port_Btn.setText(_translate("MainWindow", "Open Selected  Port"))
        self.ser_Port_Info_LabCrl.setText(_translate("MainWindow", "TextLabel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
